name: Build and test Conan consumer
on:
  push:

jobs:
  build:
    strategy:
         matrix:
           os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and setup Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true

      - name: Build
        run: |
          conan build HeaderOnly --build=missing --options geometry_provider="none"