name: Build and test Conan consumer
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and setup Conan
        uses: conan-io/setup-conan@v1

      - name: Build
        run: |
          conan build HeaderOnly --build=missing --options geometry_provider="none"